fix: trigger error when cacnnot get version in regi

diff --git a/.github/workflows/deploy-package.yml b/.github/workflows/deploy-package.yml
--- a/.github/workflows/deploy-package.yml
+++ b/.github/workflows/deploy-package.yml
@@ -50,6 +50,11 @@ jobs:
         run: |
           PACKAGE_NAME="msw-dev-tool"
           VERSION=$(npm view $PACKAGE_NAME version)
+          if [ -z "$VERSION" ]; then
+            echo "ERROR: Cannot get $PACKAGE_NAME version from npm registry."
+            exit 1
+          fi
+          echo "NPM version: $VERSION"
           echo "npm_version=$VERSION" >> $GITHUB_ENV
 
       - name: Compare and Update package.json version
